export const projects = [
  {
    title: 'ICA Edge Checkout',
    slug: 'ica-edge-checkout',
    subtitle: '2nd Place - Couchbase Offline Resilience Hackathon',
    description:
      'An edge-first, offline-first self-checkout system built for grocery retail with automatic sync and real-time monitoring.',
    content:
      'Built for the Couchbase Edge Resilience Hackathon, ICA Edge Checkout is a three-app system simulating a grocery store that keeps running even when the network goes down. The architecture splits into a FastAPI backend with async SQLite (WAL mode) as the local source of truth, a React self-checkout terminal with offline transaction caching in localStorage, and a real-time operations dashboard. The core engineering challenge was designing the offline-first sync pipeline: terminals detect connectivity loss via heartbeat monitoring, queue transactions locally with idempotency keys, and batch-sync them when connectivity returns - with the backend enforcing deduplication via unique constraints. Other technical highlights include ECDSA-signed QR codes for a mobile Scan & Pay flow (Web Crypto API on the client, DER conversion on the server), invoice payment handling with membership verification, and best-effort Couchbase Cloud sync as a resilient cloud backup layer that never blocks the checkout flow.',
    tech: 'Python, FastAPI, SQLite, React, Vite, Couchbase, ECDSA, JWT, WebSocket',
    image: 'ica1.png',
    images: ['ica1.png', 'ica2.png', 'ICA-architecture.png'],
    video: 'https://drive.google.com/file/d/1s2-XHfmwlcPcY6Fcrg25ikvL-Vc1D9w2/preview',
    order: 1,
    siteLink: null,
    githubLink: null,
    tags: ['Fullstack'],
    featured: true,
    hackathon: { place: 2 },
    role: 'Lead feature developer (25 of 63 commits, ~40%). Built the admin dashboard with live stats and settings UI, payment systems (Swish, invoice via SMTP, card toggles), offline price overrides with inventory tracking, and Couchbase Cloud sync integration. Core platform was built by a teammate; I drove all feature development, admin tooling, and edge capabilities. Team of 3.',
  },
  {
    title: 'Innovation Airlock',
    slug: 'innovation-airlock',
    subtitle: '3rd Place - Transcom Hackathon',
    description:
      'A self-service deployment gateway that lets non-engineers drag-and-drop HTML projects and get a live URL on GCP, with AI-powered security scanning and Terraform-backed IaC.',
    content:
      'Built for the Transcom hackathon, Innovation Airlock solves a real problem: Sales and Solutions teams "vibe code" HTML widgets with AI tools like Gemini and Lovable, but have no way to share them beyond localhost. The system provides a drag-and-drop interface where users upload a ZIP of their static site, which then goes through three concurrent AI-powered checks (security, cost estimation, and brand alignment) using Claude Sonnet via the Anthropic API. If approved, the backend auto-generates a Dockerfile, builds a container via Google Cloud Build, pushes it to Artifact Registry, and deploys it to Cloud Run - all orchestrated through dynamically generated Terraform with per-deployment workspaces and GCS-backed state. The architecture splits into a React frontend with a state-machine-driven UI, a FastAPI backend with async SQLite, and a full Terraform IaC pipeline. Demo deployments auto-expire after 1 hour via a background cleanup loop.',
    tech: 'React, TypeScript, Vite, Python, FastAPI, SQLite, Terraform, GCP, Cloud Run, Cloud Build, Artifact Registry, Anthropic API, Docker',
    image: 'transcom1.png',
    images: ['transcom1.png', 'transcom-architecture.png'],
    video: 'https://storage.googleapis.com/temp-public-sharing/Transcom%20Hackathon%20intro%20(3).mp4',
    order: 2,
    siteLink: null,
    githubLink: null,
    tags: ['Fullstack', 'Cloud'],
    featured: true,
    hackathon: { place: 3 },
    role: 'Project founder and top contributor (24 of 63 commits). Built the full-stack deployment gateway from scratch (FastAPI + React + Terraform), the admin panel with policy management and audit logging, partner brand checking via HTML scraping, billing dashboard, and GCP infrastructure configuration. Team of 7.',
  },
  {
    title: 'AIX Token Intelligence Platform',
    slug: 'aix-token-intelligence',
    subtitle: 'Production on-chain monitoring, analytics, and risk scoring with Terraform-managed GCP infrastructure',
    description:
      'An on-chain analytics platform tracking AIX token activity across Base Mainnet with automated monitoring, risk scoring, and behavioral wallet classification.',
    content:
      'Built an on-chain analytics platform for AIX token activity across Base Mainnet, split into two production systems. The automated monitoring layer runs 4 scheduled Cloud Run Jobs reading live smart contract state via RPC, with event log indexing using block-range pagination (500k blocks/batch) and parallel contract reads with batching. Infrastructure is fully Terraform-managed: Cloud Scheduler, Secret Manager, Artifact Registry, dedicated service accounts, with OAuth vs OIDC auth distinctions and cross-region constraints. Daily Slack reporting and conditional alerting keep the team informed. The token intelligence layer consists of 67+ Dune SQL queries decoding raw on-chain events at ABI level (byte offset extraction), including a 28-query ApeBonds pipeline for bond purchases, redemptions, and whale behavioral profiling, and a 13-query Top 500 dashboard with composite risk scoring (4-factor, 0-100 scale) and behavioral classification across 6 labels (ACCUMULATOR, EXITING, PROFIT_TAKER, etc.). A separate Season 2 community dashboard tracks bridging activity, TVL, token migration flows, staking pool performance, and transaction volumes across Ethereum, Base, and Polygon. Data quality is enforced through golden trace verification with fixture-based testing, documented invariants, and 4 root-cause-analyzed bug fixes.',
    tech: 'Terraform, GCP, Cloud Run, Cloud Scheduler, Secret Manager, Node.js, viem, Dune Analytics, SQL, Base Mainnet, Ethereum, Polygon, Chainlink CCIP',
    image: 'dune1.png',
    images: ['dune1.png', 'aix2.png', 'aix-architecture.png'],
    order: 3,
    siteLink: 'https://dune.com/planetix_team_official/aix-token-season-2',
    githubLink: null,
    tags: ['Data', 'Cloud'],
    featured: true,
    hackathon: null,
  },
  {
    title: 'Nuxtermind',
    slug: 'nuxtermind',
    subtitle: 'Real-time multiplayer game with WebSocket architecture',
    description:
      'A real-time multiplayer code-breaking game built on event-driven WebSocket architecture.',
    content:
      'Nuxtermind is a modern take on the classic Mastermind game, rebuilt as a real-time multiplayer experience. The core technical challenge was designing an event-driven architecture using Socket.io to handle matchmaking, game state synchronization, and conflict resolution across concurrent sessions. Supabase provides the persistence layer for user data and match history. The game logic was designed to be stateless on the client and authoritative on the server, preventing desync issues and enabling future game modes without architectural changes. Character selection and timed rounds add gameplay depth while stress-testing the real-time pipeline under load.',
    tech: 'Vue 3, Nuxt, Supabase, Socket.io, Pug, Tailwind',
    image: 'nuxtermind1.png',
    order: 4,
    siteLink: 'https://nuxtermind.vercel.app/',
    githubLink: 'https://nuxtermind.vercel.app/',
    tags: ['Web', 'Fullstack'],
    featured: true,
    hackathon: null,
  },
  {
    title: 'Parking Time',
    slug: 'parking-time',
    subtitle: 'Production company website with CMS integration and i18n',
    description:
      'A multilingual production website with headless CMS, SEO optimization, and internationalization.',
    content:
      "Parking Time is a production company website delivered through a full agile process with weekly client presentations. The architecture uses Next.js with next-intl for internationalization across all routes, and Sanity as a headless CMS so the client can manage content independently. GROQ queries power dynamic content fetching with minimal payloads. Key engineering decisions included structuring the i18n routing to preserve SEO across languages, implementing Google reCAPTCHA v3 for form protection, and optimizing build caching and image loading to handle the client's media-heavy content. Shipped on schedule with a team of four developers collaborating alongside UX designers.",
    tech: 'TypeScript, Next.js, React, Tailwind, Google Recaptcha V3, Sanity, GROQ, Internationalization',
    image: 'parking.png',
    order: 5,
    siteLink: 'https://parking-time.vercel.app/en',
    githubLink: 'https://github.com/indiano881/Parking-time',
    tags: ['Web'],
    featured: true,
    hackathon: null,
  },
  {
    title: 'Pandorum',
    slug: 'pandorum',
    subtitle: 'E-commerce platform with client-side state management',
    description:
      'An e-commerce storefront with wishlist functionality powered by React Context API.',
    content:
      "Pandorum is an e-commerce platform where users browse a curated product catalog with wishlist functionality. The state management layer was built from scratch using React's Context API - a deliberate architectural choice to keep the bundle lean and avoid external dependencies for a contained state graph. Context providers handle authentication, cart, and wishlist state with clean separation of concerns. The UI features a splash screen animation calibrated across breakpoints and a product browsing flow designed around engagement metrics. The project demonstrates that lightweight state solutions can be the right tool when the complexity profile fits.",
    tech: 'Next.js, Tailwind CSS, React Context API, Splash Screen Animation',
    image: 'pandorum.png',
    order: 6,
    siteLink: 'https://store-context.vercel.app/',
    githubLink: 'https://github.com/indiano881/store-context/tree/main',
    tags: ['Web'],
    featured: false,
    hackathon: null,
  },
  {
    title: 'Economic MUI',
    slug: 'economic-mui',
    subtitle: 'Data visualization dashboard with real-time API integration',
    description:
      'An interactive dashboard for economic data analysis with dynamic charting and real-time API feeds.',
    content:
      "Economic MUI is a single-page dashboard that visualizes economic data through interactive charts and configurable layouts. The architecture separates data fetching, transformation, and rendering into distinct layers - API responses are normalized into a common schema before hitting the charting components, making it straightforward to add new data sources. Material-UI's Grid system handles the responsive layout. The main performance challenge was managing React re-renders during real-time data updates; this was solved with memoization strategies and selective state subscriptions to keep chart interactions smooth even with frequent data refreshes.",
    tech: 'TypeScript, React, Material-UI, Single Page Application',
    image: 'economic.png',
    order: 7,
    siteLink: 'https://economi-mui.netlify.app/',
    githubLink: 'https://github.com/indiano881/economicMUI',
    tags: ['Data', 'Web'],
    featured: false,
    hackathon: null,
  },
]
